### PR TITLE
Update contentscript.js

### PR DESCRIPTION
**Pull request by castles**
Update delete code to match spec so it works with the latest version of Chrome.

### CODE REVIEW

**Comment by tomayac** [comment]
Thanks for the PR! The `remove()` method already exists behind a flag and [will be enabled in M110](https://groups.google.com/a/chromium.org/g/blink-dev/c/tESXuOfqQMQ/m/-eGUcHguAgAJ). Since this is a bleeding edge extension for a bleeding edge feature, I prefer to leave the code simpler, that is, as is.

**Comment by tomayac** [comment]
(M110 will go to stable on Feb 1, 2023, so not a long wait.)

**Comment by castles** [comment]
Oh sweet. remove() will make things much easier for my other projects. Thanks for the info.

**Comment by tomayac** [comment]
(This came up again in #4, but closing for the same reasons.)

**Pull request closed without merging**
